In [10]:
import numpy as np



### Implementation of singal neuron

In [8]:
class Neuron(object):
#  """A simple feed-forward artificial neuron.
#  Args:
#  num_inputs (int): The input vector size / number of input values.
#  activation_fn (callable): The activation function.
#  Attributes:
#  W (ndarray): The weight values for each input.Computer Vision and Neural Networks Chapter 1
# [ 31 ]
#  b (float): The bias value, added to the weighted sum.
#  activation_fn (callable): The activation function.
#  """
    def __init__(self, num_inputs, activation_fn):
        #  # Randomly initializing the weight vector and bias value:
        self.W = np.random.rand(num_inputs)
        self.b = np.random.rand(1)
        self.activation_fn = activation_fn
    def forward(self,x):
        #  """Forward the input signal through the neuron."""
        z = np.dot(x, self.W) + self.b
        return self.activation_fn(z)

In [12]:
# Fixing the random number generator's seed, for reproducible results:
np.random.seed(42)
# Random input column array of 3 values (shape = `(1, 3)`)
x = np.random.rand(3).reshape(1, 3)
# > [[0.37454012 0.95071431 0.73199394]]
# Instantiating a Perceptron (simple neuron with step function):
step_fn = lambda y: 0 if y <= 0 else 1
perceptron = Neuron(num_inputs=x.size, activation_fn=step_fn)
# > perceptron.weights = [0.59865848 0.15601864 0.15599452]
# > perceptron.bias = [0.05808361]
out = perceptron.forward(x)
print(out)

1


### Implementation of neural network

In [14]:
import numpy as np
class FullyConnectedLayer(object):
    
#  """A simple fully-connected NN layer.
#  Args:
#  num_inputs (int): The input vector size/number of input values.
#  layer_size (int): The output vector size/number of neurons.
#  activation_fn (callable): The activation function for this layer.
#  Attributes:
#  W (ndarray): The weight values for each input.
#  b (ndarray): The bias value, added to the weighted sum.
#  size (int): The layer size/number of neurons.
#  activation_fn (callable): The neurons' activation function.
    def __init__(self, num_inputs, layer_size, activation_fn):
        self.W = np.random.standard_normal((num_inputs, layer_size))
        self.b = np.random.standard_normal(layer_size)
        self.size = layer_size
        self.activation_fn = activation_fn
    def forward(self, x):
        z = np.dot(x, self.W) + self.b
        return self.activation_fn(z)


In [17]:
np.random.seed(42)
# Random input column-vectors of 2 values (shape = `(1, 2)`):
x1 = np.random.uniform(-1, 1, 2).reshape(1, 2)
# > [[-0.25091976 0.90142861]]
x2 = np.random.uniform(-1, 1, 2).reshape(1, 2)
# > [[0.46398788 0.19731697]]
relu_fn = lambda y: np.maximum(y, 0) # Defining our activation function
layer = FullyConnectedLayer(2, 3, relu_fn)
# Our layer can process x1 and x2 separately...
out1 = layer.forward(x1)
# > [[0.28712364 0. 0.33478571]]
out2 = layer.forward(x2)
# > [[0. 0. 1.08175419]]
# ... or together:
x12 = np.concatenate((x1, x2)) # stack of input vectors, of shape `(2, 2)`
out12 = layer.forward(x12)
# > [[0.28712364 0. 0.33478571]
# [0. 0. 1.08175419]]
print(out12)
#stack of input is termed as batch

[[0.28712364 0.         0.33478571]
 [0.         0.         1.08175419]]


In [21]:
from tensorflow.keras import mnist
np.random.seed(42)
# Loading the training and testing data:
X_train, y_train = mnist.train_images(), mnist.train_labels()
X_test, y_test = mnist.test_images(), mnist.test_labels()
num_classes = 10 # classes are the digits from 0 to 9
# We transform the images into column vectors (as inputs for our NN):
X_train, X_test = X_train.reshape(-1, 28*28), X_test.reshape(-1, 28*28)
# We "one-hot" the labels (as targets for our NN), for instance, transform

y_train = np.eye(num_classes)[y_train]

ImportError: cannot import name 'mnist' from 'tensorflow.keras' (C:\Users\hp\anaconda3\lib\site-packages\tensorflow\keras\__init__.py)

In [25]:
import tensorflow.keras as keras

In [27]:
keras.minst

AttributeError: module 'tensorflow.keras' has no attribute 'minst'